### ISSUE TITLE
Support SPDX 2.3

### ISSUE THREAD

**Issue by mmurto** [doubleopen-project/spdx-rs#10]
Reference: https://github.com/spdx/spdx-spec/issues/691#issuecomment-1154198748

**Comment by alilleybrinker** [comment]
I have a draft PR, which I expect to be opening sometime this week on this repository, which implements 2.3!

**Comment by alilleybrinker** [comment]
Looks like I broke the commitlint rule (my apologies; didn't realize it was there). Is there anything you'd like from me to fix it?

**Comment by mmurto** [comment]
> Looks like I broke the commitlint rule (my apologies; didn't realize it was there). Is there anything you'd like from me to fix it?

I squash merged it and fixed the message there, so no need to do anything. :) I also release v0.5.3 with the improvement. Thanks again for your contribution!

**Comment by alilleybrinker** [comment]
Excellent! Thanks so much, and I'm glad the change was helpful 😄
